spring:
  application:
    name: tramites-service
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tramites_db
      auto-index-creation: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gestiontramites: DEBUG
    org.springframework.data.mongodb: DEBUG

microservicios:
  usuarios-service:
    url: http://localhost:8082